# Unit 10 {-}

##  onsolidation and Evaluatio{-}

### Unit 10 (Week 10){-}
#### Thursday, Sept. 16 - Wednesday, Sept. 22{-}
###### Things to do this week...{-}

- Meet in Zoom [badge label="Thursday, September 16 - 11:30 AM PDT" url="https://www.timeanddate.com/worldclock/fixedtime.html?msg=LDRS+663+Meeting&iso=20210916T1130&p1=1109&ah=1&am=30"" /]  
- **Read** [**Facilitating Learning and Change in Groups**](https://infed.org/mobi/facilitating-learning-and-change-in-groups-and-group-sessions/)  
- **Read** [**What is a Group?**](https://infed.org/mobi/what-is-a-group/)  
- **Read** [**Comfort Zone to Performance Management**](https://www.researchgate.net/publication/228957278_From_Comfort_Zone_to_Performance_Management)  
- **Read** [**Core Competencies**](https://www.iaf-world.org/site/professional/core-competencies)  
- **Watch** [Liberating Structures](https://player.vimeo.com/video/364868276)  
- **Visit** [**What, So What, Now What? W³**](http://www.liberatingstructures.com/9-what-so-what-now-what-w/)  
:fa-check: Please complete these items by [badge label="Wednesday, September 22" url="https://www.timeanddate.com/worldclock/fixedtime.html?msg=LDRS+663+Meeting&iso=20210916T1130&p1=1109&ah=1&am=30"" /]  

---

# Unit 9:{-}


## Overview{-}




##Learning Outcomes{-}
-----------------

When you have completed this unit, you should be able to:

-   

##Activity Checklist{-}
------------------

Here is a checklist of learning activities you will benefit from in completing
this unit. You may find it useful for planning your work.

|  ☑  | **Activities**                                                                                                     | **Time**  |
|---|--------------------------------------------------------------------------------------------------------------------|-----------|
|   | Activity 9.1:                                                          | 1 hour    |
|   | Activity 9.2:                                                              | 3-5 hours |
|   | Activity 9.3:  | 3-5 hours |
|   | Activity 9.4:    | 3-5 hours |
|   | **Assignment:**                                            | 3-5 hours |
|   | **Assignment:**                                           | 3-5 hours |

## Resources{-}
---------

Here are the resources you will need to complete this unit.

## Learning Activities{-}

### Activity 9.1. GATHERING: Class meeting with Professor.

In this week’s conference meeting, your professor will provide a 60 minute talk
summarizing ‘The Advantage’ and talking about the role of the team in
establishing and maintaining a positive peer culture within an organization.

This 1 hour online session will be recorded for future reference.

**Unit slides:**

In order to prepare for the meeting, you are invited to view the [Unit 9 Slides](https://gitpitch.com/TWUOnline/gitpitch-decks/master?grs=github&t=black&p=LDRS502-9). Your instructor will go through this presentation
during the gathering, so as you view the slideshow, be sure to jot down notes
and questions.

[button url="https://gitpitch.com/TWUOnline/gitpitch-decks/master?grs=github&t=black&p=LDRS502-9" target="_blank" label="Unit 9 Slides" type="info" classes="external-link"]_  

---

### Activity 9.2: COMMUNITY BUILDING: Everest Simulation II

In this activity, you will take the Everest Challenge Simulation for the second
time. Check with your instructor on how we will alter the roles and nature of
the challenge for the second iteration of the Everest Challenge.

At the conclusion of this week, you will have to provide your personal reactions
and reflections on the experience of the Everest Simulation. See the specific
questions in the Assessment section of this unit and post your responses in the
weekly Moodle forum.

---

### Activity 9.3: PERSONAL STUDY AND REFLECTION

Read Chapter 14 in your Levi textbook as well as Patrick Lencioni’s book, *The
Advantage* (240 pages). Take notes to help you complete the assessments in this course.

---

### Activity 9.4: ASSEMBLING AS A TEAM

In week 9, you should be working together as a team to fine-tune your project
and prepare for the class presentation in week 10.

---

## Unit 9 Summary{-}

In Unit 9, you had the opportunity to learn about culture in teams and teamwork.
You saw how different cultures can affect teams and why different cultures may
clash in a team dynamic. You looked at organizational culture and teamwork and
how to predict team success. You also covered the dimensions of international
culture and how to create an effective transnational team.

## Unit 9 Assessment


### Assignment: Everest Simulation Personal Reflection (part of class participation grade (10%)

**Date Due: At the end of week 8 and at the end of week 9 (submit twice)**

Please respond to the following self and team reflection questions regarding
your personal experiences completing the Everest Simulation with your team. Your
final submission should be 2-3 pages in length.

Please describe your role in the Everest simulation and describe the level of
engagement you had in the experience.

1.  How do you believe your engagement and interaction in the Everest Simulation
    aligned or did not align with your Birkman Assessment?

2.  Cognitive/Intellectual Learning. To what extent did you learn about yourself
    through the Everest Simulation?

    1.  What did you learn about yourself and your teammates through this
        experience?

3.  Emotional Learning. How did you feel as you went through the Everest
    Simulation? Your you surprised at all about the emotions you felt throughout
    the simulation?

4.  Team Experience. How did you feel about your Team's Performance on the
    Everest Simulation?

    1.  Did you feel as if everyone contributed in a balanced and proportionate
        way in the Everest Simulation?

    2.  b. Did your team experience any conflict through the Everest Simulation?
        If so, please describe how you were able to manage the conflict?

    3.  Do you feel that the conflict related to personalities, vests interests,
        conflicting priorities, external pressures or role conflicts?

### Assignment: Class Presentation (10%)

In the final week of classes, your group will present your Team Project,
including aspects of the team process as well as the outcome of the team
engagement related to the problem or opportunity.

*About Presentations:*

**Presentations are visual representations of ideas, concepts, innovations,
plans, or solutions. As such they need to be appealing to keep the interest of
the audience. In order to produce good presentations, the following key factors
should be considered:**

1.  **Presentations should not be read from a paper.** Writing a technical
    report or paper is a different medium of communication than presenting
    orally. The goal of a presentation is to get a few key points across to an
    audience, not to overwhelm people with research and detail. Always assume
    people will read the technical paper if they are interested in doing so.

2.  **Presentations must be visually appealing.** Interspersing pictures, video,
    graphics, charts, tables all help to keep the listener engaged in the
    presentation.

3.  **Presentations must be readable.** When you choose a font size for a
    presentation, bigger is always better. Assume your grandma is looking at the
    presentation and her eyesight is not as good as it used to be. In addition,
    the key words you choose for a presentation should go at the top of the
    slides.

4.  **Presentations must be succinct.** Most people only have an attention span
    of a few seconds. Key points must be emphasized at least 3 times for the
    audience to get it. As a result, there are very few points that you can
    reasonably cover in a presentation.

5.  **Presentations must compel through story.** You must find ways to tell a
    compelling story through your presentation. People need to emotionally
    connect to the issue, problem, solution or opportunity that you are
    presenting. In order to do this, you need to present a strong and compelling
    (single idea) story to the audience.

6.  **Every presenter can improve.** If you are unsure about a presentation
    format or style, research online presentations and gauge how they made you
    feel and how compelling they were. Learn from what worked in other
    presentations in order to improve your ability to present meaningfully.
    Finally, practice, practice, practice. You should go through your online
    presentation one or two times before going live to test everything out, to
    make sure all the transitions between presenters are smooth.

**The rules for the online presentations for 502OL are as follows:**

1.  Each team has to use ppt, pdf, Prezi, or some format that will organize
    their presentation for the class. The presentation needs to be uploaded to
    MOODLE at least 1 hour before the presentation in order to ensure there are
    no glitches during the zoom conference call.

2.  Each member of the team must play an active role in the presentation. They
    need to take some measurable and observable role in the presentation itself
    so the professor can grade their involvement.

3.  The presentations must be fully reflective of the team-based project
    completed throughout the 10 week online course.

4.  Presenters should be dressed and equipped for a formal presentation in the
    virtual space. Presenters should model the presentation as if they are
    presenting to the board of directors of the company or organization that has
    a problem or is looking to engage an opportunity.

5.  The presentation should cover both aspects of the team process as well as
    the outcome of the team engagement related to the problem or opportunity.
    The structure for this should be about 1/3 of the time devoted to the team
    processes: Team Charter, Roles and Responsibilities, Conflict resolution
    structure, etc., and 2/3 should revolve around the organizational problem or
    opportunity, what research was conducted and what conclusions or directions
    are supported by the team.

6.  An appeal for change needs to be made to the class at the conclusion of the
    project.

7.  Presentations must conclude at the 30 minute mark or they will be cut off.
    There will be no tolerance for using other people’s time for your
    presentation.

### Assignment: Team Project (30%)

**Date Due: Within 1 week of the final course presentation**

**The final team project is the capstone assignment for LDRS 502. In order to
receive a high grade for the capstone project, you must provide an excellent,
research-based summary of the following two main processed and outcomes:**

1.  The Team--you need to describe the topic, mission vision, values, charter,
    and conflict management process for the team. AND

2.  The recommended solution, list of solutions, or recommendations related to
    the problem or opportunity as a result of your team process throughout this
    course.

**In order to complete this assignment effectively, you should have the
following key sections written in your paper:**

1.  APA style title page to the team report.

2.  Executive summary of the team processes and recommendations of the team (1-2
    pages with no references...just descriptions).

3.  Sections describing the team processes, descriptions of each team member
    (maybe even pictures), their role in the team outcome, their accompanying
    Birkman score and the fit between their Birkman and their role (this section
    should be an edited or revised version of the Team Charter submission as per
    the instructor’s comments).

4.  Sections describing the Mission Vision Values of the Team, Mandate presented
    to the team (or chosen by the team), schedule of meetings and outcomes for
    the team process (this section should be an edited or revised version of the
    Team Charter submission as per the instructor’s comments).

5.  A section describing the Team Conflict Management system and some commentary
    on how effectively conflict was actually managed by the team throughout the
    process (this section should be an edited or revised version of the Team
    Conflict Management submission as per the instructor’s comments).

6.  Sections describing the outcome of the team process, what solution,
    innovation, and recommendations the team is making with support for the
    recommendation. This section should include research on the issue that was
    tackled by the team, background knowledge used to arrive at a
    recommendation, other options that were considered and dismissed by the
    team, a rationale for the recommendation made by the team, and an outcome of
    the team process.

7.  A summary and conclusion section.

8.  References.

9.  Tables and Figures as necessary to support the final team project.

10. Appendices, Endnotes, or any additional material as necessary.

In addition to the sections listed above, please pay attention to the following:

-   APA Style should be used for references, citations, page numbers, headers,
    footers, Appendices, tables and figures. There will be grace on the use of
    APA style for headings and subheadings as this is a report and not an
    academic research paper.

-   You should use the course material to support both the team processes you
    develop and the recommended solution. The Levi and Lencioni texts as well as
    lectures and class discussions should be a key part of the references you
    integrate into the final paper. Please ensure that the course textbooks,
    lectures and class discussions are properly referenced in APA style.

## Checking your Learning{-}
----------------------

Before you move on to the next unit, you may want to check to make sure that you
are able to:

-   Analyze the key aspects of highly effective teams and organizational
    cultures.

-   Explain how to enhance the team culture and organizational environment to
    achieve positive organizational results.

-   Identify both monetary and non-monetary incentives for effective team
    performance.

-   Analyze and choose effective teambuilding and team training models.
